### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by dty2** [davepkxxx/matrix_digital_rain#1]
Hey bro, I think I found a bug in your code.
About your code, I use it in my web pages, but when I refresh the web page, the matrix_digital_rain  didn't work.
The effect after refresh is black screen of web page.
I guess that you forget to initialize the variable "frames".
So I add `let frames = 0;` before ` new p5(p => {`.
And then it works !
Please check your code (I'm a tyro in javascript, maybe I was wrong, if I was wrong, sorry!!!)

**Comment by davepkxxx** [comment]
Thanks so much for catching that bug and taking the time to let me know about the issue with the matrix_digital_rain not working properly on page refresh. Your suggestion was spot on—I did miss initializing the frames variable. I've now fixed it based on your advice, and you can see the update in this commit: [e7ef73b](https://github.com/davepkxxx/matrix_digital_rain/commit/e7ef73b895f988025a3cdda90269351cd0efec02).
